### ISSUE TITLE
Cantomat, result differ from canalyzer

### ISSUE THREAD

**Issue by RasMH** [aheit/cantools#12] opened 2021-11-04 10:22 UTC
Hello
I am converting a blf-file to mat with the help of three dbc-files. By comparing the output to a Canalyzer trace, I see that some message and signal names in the mat output does not match the ones shown in Canalyzer.  To better judge which one is incorrect, I have also used the python cantools utitilty and it shows the same exact output as Canalyzer.

Here is the command I use to convert:
cantomat -b2 -d BBA.dbc  -b3 -d BBB.dbc -b11 -d BBC.dbc -B cantraffic.blf -pbm --verbose -t1 -m out.mat
Here is the relevant output with cantomat:

Name: Ch11_DAQ1_TESTER_T_DAQ1_data
 Rank: 2
Dimensions: 33739 x 2
Class Type: Double Precision Array
 Data Type: IEEE 754 double-precision
{
0.000326 3.84469e+09
0.001586 13
0.002894 3.35544e+09
0.005309 2.5574e+09

In Canalyzer I have this:
![image](https://user-images.githubusercontent.com/12778717/140295913-5ec0eb7b-524f-4fae-8574-4f99a3b5ce29.png)

Issue I want to pinpoint here is that cantomat output says DAQ1_TESTER_T instead of the expected DAQ1_TESTER_E. Signal values differ as well.  Timestamps match as you see (and there are no other signals with the same timestamp). This is not the only frame that is different. I see a mismatch on about 40 frames compared to cantools. I have tried, but not been able to find a pattern, I get the wrong name on different channels and on both extended and short ids.

I may not be able to share the blf or dbc files, but I would be glad to assist in figuring out what the issue may be. 

Cantomat version is 0.31. I compiled it on Ubuntu 20.04 under windows subsystem for linux (WSL).
kind regards,
Rasmus

**Comment by aheit** [comment] 2021-11-20 18:43
Hello Rasmus,

 

thanks for the report and sorry for the late response.

 

Let me try to understand what is going wrong:

*	We are looking at the data on channel 11 to which BBC.dbc is assigned
*	During BLF decoding,  cantomat matches DAQ1_TESTER_T to some message and translates the contained signals incorrectly. This can be seen in the matdump output.
*	CANape and other tools match DAQ1_TESTER_E to the same message and translate the signal values correctly. This can be seen in the CANape screenshot

 

Let me try to ask some questions first. 

*	You wrote “Issue I want to pinpoint here is that cantomat output says DAQ1_TESTER_E instead of the expected DAQ1_TESTER_T”. This seems to contradict the mat output which says “Ch11_DAQ1_TESTER_T_DAQ1_data”. Is there a mistake in the description?
*	What is the difference between DAQ1_TESTER_R and DAQ1_TESTER_T in the dbc file? Do they have different CAN ids? Can you tell me their numerical ids?
*	Debugging the issue might be difficult without the actual files. Would you be able to provide reduced files with just the relevant data for root causing?

 

Thanks,

Andreas

 

Von: RasMH ***@***.***> 
Gesendet: Donnerstag, 4. November 2021 11:23
An: aheit/cantools ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [aheit/cantools] Cantomat, result differ from canalyzer (Issue #12)

 

Hello
I am converting a blf-file to mat with the help of three dbc-files. By comparing the output to a Canalyzer trace, I see that some message and signal names in the mat output does not match the ones shown in Canalyzer. To better judge which one is incorrect, I have also used the python cantools utitilty and it shows the same exact ouput as Canalyzer.

Here is the command I use to convert:
cantomat -b2 -d BBA.dbc -b3 -d BBB.dbc -b11 -d BBC.dbc -B cantraffic.blf -pbm --verbose -t1 -m out.mat
Here is the relevant output with cantomat:

Name: Ch11_DAQ1_TESTER_T_DAQ1_data
Rank: 2
Dimensions: 33739 x 2
Class Type: Double Precision Array
Data Type: IEEE 754 double-precision
{
0.000326 3.84469e+09
0.001586 13
0.002894 3.35544e+09
0.005309 2.5574e+09

In Canalyzer I have this:
 <https://user-images.githubusercontent.com/12778717/140295913-5ec0eb7b-524f-4fae-8574-4f99a3b5ce29.png> 

Issue I want to pinpoint here is that cantomat
output says DAQ1_TESTER_E instead of the expected DAQ1_TESTER_T. Signal values differ as well.
Timestamps match as you see (and there are no other signals with the same timestamp). This is not the only frame that is different. I have tried, bu not been able to find a pattern, I get the wrong name on different channels and on both extended and short ids.

I may not be able to share the blf or dbc files, but I would be glad to assist in figuring out what the issue may be.
kind regards,
Rasmus

**Comment by RasmusH-DS** [comment] 2021-11-24 10:28
Hi Andreas!
Sorry for not being fully clear. I'll try again. 
Canalyzer says that the message on timestamp 0.000326 has the name DAQ1_TESTER_E and includes only 1 signal: DAQ1_data_E. 
Cantomat,  for the same timestamp outputs the message name DAQ1_TESTER_T and the signal name is DAQ1_data (I had the flag -pmb when running cantomat)

Here are the id:s of the messages.
![image](https://user-images.githubusercontent.com/94180493/143220809-15f41f02-d234-4928-97b3-9ab4df57b73e.png)

I was able to strip the dbc-file to an absolute minimum that I can share. 
Do you have an email-adress I can send the blf and dbc-file to? I am not comfortable uploading them directly here. 

In reality more messages differed between canalyzer and cantomat, but hopefully this will be enough to find the root cause.

**Comment by aheit** [comment] 2021-11-28 16:18
Hello Rasmus,

yes, please send the files to ***@***.***

I hope I can solve the problem with the files.

Thank you and regards,
Andreas

Am Mi., 24. Nov. 2021 um 11:28 Uhr schrieb Rasmus H <
***@***.***>:

**Comment by RasmusH-DS** [comment] 2021-11-29 07:34
Hi Andreas, 
It looks like the address got scrambled during publishing. I have sent the code to your gmail-account.

**Comment by aheit** [comment] 2024-03-23 19:30
Hi Rasmus, I noticed that the issue is still open and I would like to close it. Did the commit of Dec 21, 2021 work for you?

**Comment by aheit** [comment] 2024-03-25 13:26
update of Dec 21, 2021 implemented double type signals, closing the issue.

**Closed as completed by aheit** 2024-03-25 13:26 UTC
